// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewScreech struct {
	UserID  string `json:"user_id"`
	Content string `json:"content"`
}

type NewUser struct {
	Name string `json:"name"`
}
